version: '3.7'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.4
    user: root
    command:
      - e
      - --strict.perms=false

    volumes:
      - ./filebeat-config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped