name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata: ~
  - add_cloud_metadat: ~

monitoring:
  enabled: true
  elasticsearch:

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  #Create User in Kibana UI and provide credentials
  #username: beatusr  
  #password: beat1234
http:
  enabled: true
  host: 0.0.0.0